// Generated by https://quicktype.io

export interface ICommissionStatement {
    Vendor_No: string;
    Entry_No: number;
    Posting_Date: string;
    Document_Type: string;
    Document_No: string;
    Description: string;
    External_Document_No: string;
    Amount: number;
}
