// Generated by https://quicktype.io
export interface IEligibiity {
    EmployeeID: string;
    Age: string;
    Reason: string;
    Tenor: string;
    Status: string;
    DOB: string;
    FullName: string;
    AssignmentStatus: string;
    Gender: string;
    Job: string;
    Organization: string;
    HireDate: string;
    Department: string;
    Ministry: string;
    SSN: string;
    BankName: string;
    BankBranch: string;
    Location: string;
    District: string;
    Region: string;
    SSNExempt: string;
}
